/**
 * @file Framework.h
 * @copyright 2019 Istituto Italiano di Tecnologia (IIT). This software may be modified and
 * distributed under the terms of the GNU Lesser General Public License v2.1 or any later version.
 */

// Autogenerated by bipedal-locomotion-framework project
//
// This is an automatically generated file.
// Please DO NOT edit this file manually.

#ifndef BIPEDAL_LOCOMOTION_FRAMEWORK_H
#define BIPEDAL_LOCOMOTION_FRAMEWORK_H

#include <BipedalLocomotion/GenericContainer/Vector.h>
#include <BipedalLocomotion/GenericContainer/TemplateHelpers.h>
#include <BipedalLocomotion/YarpUtilities/Helper.h>
#include <BipedalLocomotion/ParametersHandler/IParametersHandler.h>
#include <BipedalLocomotion/ParametersHandler/YarpImplementation.h>
#include <BipedalLocomotion/Estimators/RecursiveLeastSquare.h>
#include <BipedalLocomotion/System/Advanceable.h>
#include <BipedalLocomotion/System/DynamicalSystem.h>
#include <BipedalLocomotion/System/FloatingBaseSystemDynamics.h>
#include <BipedalLocomotion/System/ContactWrench.h>
#include <BipedalLocomotion/System/LinearTimeInvariantSystem.h>
#include <BipedalLocomotion/System/Integrator.h>
#include <BipedalLocomotion/System/FixStepIntegrator.h>
#include <BipedalLocomotion/System/ForwardEuler.h>
#include <BipedalLocomotion/System/FloatingBaseSystemKinematics.h>
#include <BipedalLocomotion/Planners/Contact.h>
#include <BipedalLocomotion/Planners/ContactList.h>
#include <BipedalLocomotion/Planners/ContactPhase.h>
#include <BipedalLocomotion/Planners/ContactPhaseList.h>
#include <BipedalLocomotion/ContactModels/ContactModel.h>
#include <BipedalLocomotion/ContactModels/ContinuousContactModel.h>

#endif // BIPEDAL_LOCOMOTION_FRAMEWORK_H
